Resources:
  ec2securitygroupDemo:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: demoScGr
      GroupDescription: allow all web traffic
      VpcId: vpc-07edef8e259613ff8
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 3000
          ToPort: 3000
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
        - IpProtocol: "-1"
          CidrIp: 0.0.0.0/0
  ec2Demo:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-04505e74c0741db8d
      KeyName: ec2-udemy-key
      NetworkInterfaces:
        - AssociatePublicIpAddress: true
          DeviceIndex: "0"
          GroupSet:
            - !Ref ec2securitygroupDemo
          SubnetId: subnet-0f0d96368795e0aa0
      Tags:
        - Key: Project
          Value: udacity
