---
- name: "update apt packages."
  become: true
  apt:
    update_cache: yes

- name: "upgrade packages"
  become: true
  apt:
    upgrade: yes

- name: auto remove dependencies no longer needed
  become: true
  apt:
    autoremove: yes

- name: install nodejs npm
  become: true
  apt:
    name:
      - nodejs
      - npm
    state: latest

- name: install pm2
  become: true
  shell:
    cmd: npm install pm2@latest -g

- name: This command will create the web directory
  shell:
    cmd: mkdir ~/web

- name: Initialize node server
  copy:
    src: index.js
    dest: ~/web/index.js

- name: Start the web server
  become: true
  shell:
    cmd: pm2 start ~/web/index.js -f